name: PostMan Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install dependencies
        run: npm install
      - name: Install newman
        run: npm install -g newman
      - name: Run API & PostMan tests
        run: |
          npm start & sleep 2
          newman run ./GITHUBCI.postman_collection.json
          kill 9 `lsof -i:42069 -t`
